// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostaCitasWeb.Data;

#nullable disable

namespace PostaCitasWeb.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524233030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostaCitasWeb.Entities.AvisoAtencionInmediata", b =>
                {
                    b.Property<int>("AvisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvisoId"));

                    b.Property<int>("EstadoAviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("AvisoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("AvisosAtencionInmediata", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<bool>("EsSobrecupo")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoCita")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrigenReserva")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistradaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("CitaId");

                    b.HasIndex("EstadoCita");

                    b.HasIndex("PacienteId");

                    b.HasIndex("RegistradaPorUsuarioId");

                    b.HasIndex("SlotId");

                    b.HasIndex("PacienteId", "SlotId")
                        .IsUnique()
                        .HasFilter("[EstadoCita] IN (0, 1, 2)");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UPSId")
                        .HasColumnType("int");

                    b.HasKey("EspecialidadId");

                    b.HasIndex("UPSId");

                    b.ToTable("Especialidades", (string)null);

                    b.HasData(
                        new
                        {
                            EspecialidadId = 1,
                            Activa = true,
                            DuracionMinutos = 20,
                            Nombre = "Medicina General",
                            UPSId = 1
                        },
                        new
                        {
                            EspecialidadId = 2,
                            Activa = true,
                            DuracionMinutos = 25,
                            Nombre = "Odontología",
                            UPSId = 2
                        },
                        new
                        {
                            EspecialidadId = 3,
                            Activa = true,
                            DuracionMinutos = 20,
                            Nombre = "Obstetricia",
                            UPSId = 3
                        });
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.HistorialEstadoCita", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("HistorialId");

                    b.HasIndex("CitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEstadosCita", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CMP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MedicoId");

                    b.HasIndex("CMP")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PostaAsociadaId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneSIS")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.ProgramacionOperativa", b =>
                {
                    b.Property<int>("ProgramacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramacionId"));

                    b.Property<int>("CreadaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CuposTotal")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Habilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("ProgramacionId");

                    b.HasIndex("CreadaPorUsuarioId");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId");

                    b.ToTable("ProgramacionesOperativas", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.SlotDisponible", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("int");

                    b.Property<int>("CuposTotal")
                        .HasColumnType("int");

                    b.Property<bool>("EsSobrecupo")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ProgramacionId")
                        .HasColumnType("int");

                    b.HasKey("SlotId");

                    b.HasIndex("EsSobrecupo");

                    b.HasIndex("ProgramacionId");

                    b.ToTable("SlotsDisponibles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Slots_CuposDisponibles", "[CuposDisponibles] >= 0");
                        });
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketId");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Triaje", b =>
                {
                    b.Property<int>("TriajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriajeId"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<int>("EnfermeriaUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PresionDiastolica")
                        .HasColumnType("int");

                    b.Property<int>("PresionSistolica")
                        .HasColumnType("int");

                    b.Property<decimal>("Talla")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("TriajeId");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("EnfermeriaUsuarioId");

                    b.ToTable("Triajes", (string)null);
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.UPS", b =>
                {
                    b.Property<int>("UPSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UPSId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UPSId");

                    b.ToTable("UPS", (string)null);

                    b.HasData(
                        new
                        {
                            UPSId = 1,
                            Activa = true,
                            Nombre = "Medicina General"
                        },
                        new
                        {
                            UPSId = 2,
                            Activa = true,
                            Nombre = "Odontología"
                        },
                        new
                        {
                            UPSId = 3,
                            Activa = true,
                            Nombre = "Obstetricia"
                        });
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            Celular = "000000000",
                            DNI = "00000000",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "admin",
                            PasswordHash = "Admin123!",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.AvisoAtencionInmediata", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Cita", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostaCitasWeb.Entities.Usuario", "RegistradaPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PostaCitasWeb.Entities.SlotDisponible", "Slot")
                        .WithMany("Citas")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("RegistradaPorUsuario");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Especialidad", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.UPS", "UPS")
                        .WithMany("Especialidades")
                        .HasForeignKey("UPSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UPS");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.HistorialEstadoCita", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Cita", "Cita")
                        .WithMany("Historial")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostaCitasWeb.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Paciente", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Paciente", "Responsable")
                        .WithMany("Dependientes")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PostaCitasWeb.Entities.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("PostaCitasWeb.Entities.Paciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsable");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.ProgramacionOperativa", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Usuario", "CreadaPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostaCitasWeb.Entities.Especialidad", "Especialidad")
                        .WithMany("Programaciones")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostaCitasWeb.Entities.Medico", "Medico")
                        .WithMany("Programaciones")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadaPorUsuario");

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.SlotDisponible", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.ProgramacionOperativa", "Programacion")
                        .WithMany("Slots")
                        .HasForeignKey("ProgramacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programacion");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Ticket", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Cita", "Cita")
                        .WithOne("Ticket")
                        .HasForeignKey("PostaCitasWeb.Entities.Ticket", "CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Triaje", b =>
                {
                    b.HasOne("PostaCitasWeb.Entities.Cita", "Cita")
                        .WithOne("Triaje")
                        .HasForeignKey("PostaCitasWeb.Entities.Triaje", "CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostaCitasWeb.Entities.Usuario", "EnfermeriaUsuario")
                        .WithMany()
                        .HasForeignKey("EnfermeriaUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("EnfermeriaUsuario");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Cita", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Ticket");

                    b.Navigation("Triaje");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Especialidad", b =>
                {
                    b.Navigation("Programaciones");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Medico", b =>
                {
                    b.Navigation("Programaciones");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Dependientes");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.ProgramacionOperativa", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.SlotDisponible", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.UPS", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("PostaCitasWeb.Entities.Usuario", b =>
                {
                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
